---
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - db/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*

Style/CommandLiteral:
  EnforcedStyle: mixed

Layout/LineLength:
  Max: 140
  AutoCorrect: true
